name: campusmart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cloud_firestore: ^5.6.7
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.3.0
  iconsax_flutter: ^1.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  pay_with_paystack: ^1.0.14
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
